### ISSUE TITLE
In some cases  function OnUpdate is called before the reference m_eAI_Manager is created

### ISSUE THREAD

**Issue by BorizzK** [ralian/eai#12]
https://github.com/ralian/eai/blob/cad0310af165f13aa354e67d1c17bfc9f0a067a7/Scripts/3_Game/eAI/DayZGame.c#L28

**Comment by BorizzK** [comment]
Also spam on client

NULL pointer to instance
Class:      'DayZGame'
Function: 'OnUpdate'
Stack trace:
eAI/Scripts/3_Game/eai\dayzgame.c:28

**Comment by ralian** [comment]
Yes, sorry, that null check used to be there, I added it back.
