### ISSUE TITLE
NULL pointer to instance on server side

### ISSUE THREAD

**Issue by BorizzK** [ralian/eai#13]
https://github.com/ralian/eai/blob/cad0310af165f13aa354e67d1c17bfc9f0a067a7/Scripts/4_World/eAI/Entities/AI/eAIBase.c#L650

**Comment by BorizzK** [comment]
i dont know, why condition in string 615 returns incorrect state

**Comment by ralian** [comment]
I pushed some code that should be correct on dedicated server, but leaving this issue open until we test it

**Comment by ralian** [comment]
Closing as this has been fixed by a reversion on main
