### ISSUE TITLE
Patrols despawn instantly

### ISSUE THREAD

**Issue by Defender0518** [ralian/eai#17]
patrols are instantly deleted as the last AI withing the patrol dies.

my script.log file:
SCRIPT       : Spawning patrol at <5739.240234, 6.000000, 2137.399902>
SCRIPT       : HumanLoadout: $profile:eAI/PoliceLoadout.json exists, loading!
SCRIPT       : HumanLoadout: $profile:eAI/PoliceLoadout.json exists, loading!
SCRIPT       : SAVE CHECKSUM:1111958169
SCRIPT       : Chernarus::Weather::Fog:: ( 18.8355 ) 0.0325123
SCRIPT       : SurvivorM_Quinn:03 STS=-1 event EEKilled, player has died at STS=-1
SCRIPT       : EEKilled - processing corpse
SCRIPT       : SAVE CHECKSUM:1111958169
SCRIPT       : SurvivorM_Niki:02 STS=-1 event EEKilled, player has died at STS=-1
SCRIPT       : EEKilled - processing corpse
SCRIPT       : Chernarus::Weather::Rain::ForceEnd:: ( 18.9471 ) 0 -> 0
SCRIPT       : Deleted patrol at <5739.240234, 6.000000, 2137.399902>

**Comment by ralian** [comment]
This has been resolved with 1.12 - feel free to reopen if you still see them despawning instantly.
